import os

print(os.path.abspath("./test"))
print(os.path.split("./test"))
print(os.path.dirname("./test"))
print(os.path.basename("~/Documents/docker/redmine"))
print(os.path.commonpath(['~/Documents/docker/redmine' , '~/Documents/docker/']))
print(os.path.exists("./test"))
print(os.path.getatime("./test"))
print(os.path.getmtime("./test"))
print(os.path.getctime("./test"))
print(os.path.getsize("./test"))
print(os.path.isabs("./test"))
print(os.path.isfile("./test"))
print(os.path.isdir("./test"))
print(os.path.islink("./test"))
print(os.path.join("./test"))
print(os.path.normcase("./test"))
print(os.path.normpath("./test"))
print(os.path.realpath("./test"))
print(os.path.relpath("./test"))
print(os.path.splitdrive("./test"))
print(os.path.splitext("test.py"))
